server:
  port: 8080
spring:
  application:
    name: "template"
  webflux:
    base-path: "/"
  devtools:
    livereload:
      enabled: false
  profiles:
    active: "local"
logging:
  level:
    co.com.pragma: "DEBUG"
    org.springframework.web: "DEBUG"
springdoc:
  api-docs:
    path: "/v3/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: mydb
    schema: public
    username: myuser
    password: secret